version: "3.8"

services:
  web:
    build: .
    container_name: comfort_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: comfort_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: signup_db # Database name is 'signup_db'
      MYSQL_USER: web
      MYSQL_PASSWORD: web
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d # Auto-import jQForms.sql

volumes:
  db_data:
